#!/bin/sh

# shell
alias e="exit"
alias c="clear && l"
alias o="xdg-open"
alias v="nvim"
alias md="mkdir"
alias cm="chmod"
alias sw="source workspace"
alias fd="fdfind"
alias s="search"
alias n="note"
alias bm="bookmarks"
alias vs="code"
alias ly="lilypond"
alias ag="ag -W 255"
alias tex-pdf="tectonic.AppImage"
alias a="apparate"
alias ap="apparition"
alias utc="date -u --iso-8601=seconds | sd T ' ' | sd '\+00:00' '' | sd : -"
alias ctrl-c='xclip -sel clip'

# ls: Show hidden files by default.
alias ls="ls -a"

# cd: Navigate quickly.
alias d="cd"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

# bat
alias bat="batcat"
alias b="batcat"

# apparition
alias a="apparate"
alias ap="apparition"

# exa: Use as default list tool.
alias l="exa --color=always --group-directories-first --icons"
alias ls="exa -al --color=always --group-directories-first --icons"
alias la="exa -a --color=always --group-directories-first --icons"
alias ll="exa -l --color=always --group-directories-first --icons"
alias lt="exa -aT --color=always --group-directories-first --icons"
alias l.="exa -a --color=always --group-directories-first --icons | grep '^\.'"

# tmux: Use UTF-8 in tmux.
alias tmux="tmux -u"

# git: Use lots of shortcuts.
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gi="git initialize"
alias gl="git log"
alias gg="git graph"
alias gr="git rewrite"
alias gs="git status"
alias gu="git update"
alias gv="git view"
alias gco="git checkout"
alias gls="git ls-files"
alias grm="git remove"
alias gmv="git rename"

# dotfiles: Manage dotfiles with a bare Git repository.
alias dot="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME"

# todo.txt
alias t="bash $APPS/todo-txt/todo.sh"
alias ta="append $TODO_FILE"
alias to="nvim $TODO_FILE"
alias td="icloud-todotxt download"
alias tu="icloud-todotxt upload"

# notes
alias na="append $NOTES/$(date +%Y-%m-%d) $(date +%H:%M)"
alias no="nvim "$NOTES""

# newsboat
alias feed="newsboat -u $HOME/Schreibtisch/rss"

# docker
alias dc="docker-compose"

# downloads
alias audio-dl="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp3' -f bestaudio "
alias video-dl="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp4' -f bestvideo+bestaudio "
alias captions-dl="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp4' --all-subs --skip-download"
# alias spotify-dl="spotifydl --username $(pass spotify.com | grep -oP '(?<=username: )[^,]*') --password $(pass spotify.com | head -n 1)"

# python
alias python="python3"
alias py="python"
alias ipy="ipython"
alias isort="isort --profile=black"

# R
alias r="radian"

# docker-compose
alias dc="docker-compose"

# pass
alias otp="pass otp"

# fdupes
alias deduplicate="fdupes -r -N"

# taffy
alias tag-mp3="id3 -m '%g  -  %a  -  %l  -  %n  -  %t.mp3'"

# crypto
# alias gen-pw="openssl rand -base64"
alias gen-uuid="python -c 'import uuid; print(uuid.uuid4())'"
alias gen-ssh="ssh-keygen -t ed25519"
alias gen-pgp="gpg --default-new-key-algo 'ed25519/cert,sign+cv25519/encr' --quick-generate-key '$NAME <$EMAIL>' 'future-default' 'default' 'never'"
# alias backup-pgp="gpg --export-secret-key '$EMAIL' | paperkey --output paperkey.asc && echo '\n# Passphrase: $(pass pgp/$EMAIL | head -n 1)' >> paperkey.asc"
alias restore-pgp="paperkey --pubring publickey.asc --secrets paperkey.txt | gpg --import"
alias export-pgp="gpg --output '$EMAIL.pgp' --export-secret-key '$EMAIL'"

# zsh
alias reload="source ~/.zshrc && clear && l"

# qtile
alias qtile-reload="qtile check && qtile cmd-obj -o cmd -f reload_config"
