#!/bin/sh

alias a="apparate"
alias ap="apparition"

alias adoc='asciidoctor'
alias ag="ag -W 255"
alias az="arbeitszeit"
alias b="bat"
alias c="clear && l"
alias cm="chmod"
alias cmx="chmod +x"
alias copy='xclip -sel clip'
alias dup='fdupes -R . | sd "^" "rm \"" | sd "$" "\"" | sd "rm \"\"" ""'
alias e="exit"
alias fd="fdfind"
alias hdmi='autorandr common'
alias installs='deborphan --all-packages'
alias ipy="uvx ipython"
alias kw="isoweekdate"
alias lily="sudo watchexec -e ly lilypond *.ly"
alias logout="loginctl terminate-user 1000"
alias md="markdown"
alias m="mkdir"
alias mr="massren"
alias o="file-opener"
alias r="radian"
alias sm="smerge"
alias s="wezterm ssh"
alias tmux="tmux -u"
alias utc="date -u --iso-8601=seconds | sd T ' ' | sd '\+00:00' '' | sd : -"
alias z="exec $SHELL"

alias caps-esc='setxkbmap -option caps:swapescape'
alias caps-esc-tty="sudo loadkeys $HOME/.config/key.map"

alias d="cd"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

alias dl-audio="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp3' -f bestaudio "
alias dl-captions="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp4' --all-subs --skip-download"
# alias dl-spotify="spotifydl --username $(pass spotify.com | grep -oP '(?<=username: )[^,]*') --password $(pass spotify.com | head -n 1)"
alias dl-video="youtube-dl -o './%(upload_date)s - %(uploader)s - %(title)s.mp4' -f bestvideo+bestaudio "

alias ft-adoc-pdf='asciidoctor-pdf'
alias ft-epub-mp3='epub-to-audiobook'
alias ft-tag-mp3="id3 -m '%g  -  %a  -  %l  -  %n  -  %t.mp3'"
alias ft-tex-pdf="tectonic"

alias g="git"
alias lg="lazygit"
alias ga="git add"
alias gc="git checkout"
alias gd="git diff"
alias gg="git graph"
alias gi="git rebase -i"
alias gl="git log"
alias gls="git ls-files"
alias gm="git commit"
alias gmv="git rename"
alias gn="git note"
alias gr="git rebase"
alias grm="git remove"
alias gs="git status"
alias gu="git update"
alias gv="git view"

alias .g="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME"
alias .lg="lg --git-dir=$HOME/.dotfiles.git --work-tree=$HOME"
alias .a="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add"
alias .c="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME checkout"
alias .d="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME diff"
alias .g="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME graph"
alias .i="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME rebase -i"
alias .l="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME log"
alias .m="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME commit"
alias .n="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME note"
alias .r="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME rebase"
alias .s="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME status"
alias .u="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME update"
alias .v="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME view"
alias .ls="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME ls-files"
alias .mv="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME rename"
alias .rm="git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME remove"

alias gen-pgp="gpg --default-new-key-algo 'ed25519/cert,sign+cv25519/encr' --quick-generate-key '$NAME <$EMAIL>' 'future-default' 'default' 'never'"
alias gen-pw="openssl rand -base64"
alias gen-ssh="ssh-keygen -t ed25519"
alias gen-uuid="python -c 'import uuid; print(uuid.uuid4())'"

alias l="eza --color=always --group-directories-first --icons"
alias la="eza -a --color=always --group-directories-first --icons"
alias l.="eza -a --color=always --group-directories-first --icons | grep '^\.'"
alias ll="eza -l --color=always --group-directories-first --icons"
alias lt="eza -aT --color=always --group-directories-first --icons"

# alias pgp-backup="gpg --export-secret-key '$EMAIL' | paperkey --output paperkey.asc && echo '\n# Passphrase: $(pass pgp/$EMAIL | head -n 1)' >> paperkey.asc"
alias pgp-export="gpg --output '$EMAIL.pgp' --export-secret-key '$EMAIL'"
alias pgp-restore="paperkey --pubring publickey.asc --secrets paperkey.txt | gpg --import"

alias qtile-logs="tail -f $HOME/.local/share/qtile/qtile.log"
alias qtile-reload="qtile cmd-obj -o cmd -f reload_config"
