#!/bin/sh

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type -- "$file")" in
image/x-sony-arw)
	dcraw -W -c -e "$1" | chafa -s "$2x$3" --animate off --polite on
	;;
image/*)
	# chafa -s "$2x$3" --animate off --polite on "$1"
	# kitty +kitten icat --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" </dev/null >/dev/tty
	chafa -f kitty -s "{$w}x{$h}" "$file"
	exit 1
	;;
video/*)
	ffmpegthumbnailer -i "$1" -c png -s 512 -o - | chafa -f kitty
	;;
*/pdf)
	pdftoppm -jpeg -f 1 -singlefile "$1" | chafa -s "$2x$3" --animate off --polite on
	;;
*)
	batcat -p --theme ansi --terminal-width "$(($4 - 2))" -f "$1"
	;;
esac
