#!/bin/sh

set -eu

files="$@"

if [ -z "$files" ]; then
    git pull --rebase
    git push
else
    for file in "$@"; do
        # echo "$file"
        git add "$file"
    done
    # echo "'$@'"
    git commit -m "$files"
fi

