#!/bin/bash

process=$(ps -aux | tail -n +2 | fzf)
echo "$process"
read -p "Kill the process? [y/N]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo kill $(echo "$process" | awk '{ print $2 }')
fi
