#!/bin/bash

process=$(ps -aux | tail -n +2 | rofi -dmenu -p "Process" -i)
prompt=$(echo "$process" | sd "[ ]+" "  ")
cmd=$(printf "exit\nkill\nsudo kill" | rofi -dmenu -p "$prompt")

if [[ "$cmd" = "exit" ]]; then
    exit
fi

pid=$(echo "$process" | awk '{ print $2 }')

if [[ "$cmd" = "kill" ]]; then
    kill $pid
    exit
fi

if [[ "$cmd" = "sudo kill" ]]; then
    sudo kill $pid
fi
