#!/bin/sh

path="$1"
shift 1
name="$@"

if [ ! -z "$name" ]
then
    name=" $name"
fi

echo "Changing modified date to shot date..."
exiftool "-filemodifydate<datetimeoriginal" -r "$path"
   
echo "Renaming files to shot date..."
exiftool '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c$name.%%e" "$path"

