#!/bin/sh

chmod -x *.JPG *.jpg *.mp4 *.MTS *.mov *.MOV > /dev/null 2>&1

name="$@"
if [ ! -z "$name" ]; then
    name=" $name"
fi

if ls *.JPG 1> /dev/null 2>&1; then
    echo "Naming '.JPG' files..."
    exiftool -m '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.JPG
fi

if ls *.jpg 1> /dev/null 2>&1; then
    echo "Naming '.jpg' files..."
    exiftool -m '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.jpg
fi

if ls *.HEIC 1> /dev/null 2>&1; then
    echo "Naming '.HEIC' files..."
    exiftool -m '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.HEIC
fi

if ls *.heic 1> /dev/null 2>&1; then
    echo "Naming '.heic' files..."
    exiftool -m '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.heic
fi

if ls *.png 1> /dev/null 2>&1; then
    echo "Naming '.png' files..."
    exiftool -m '-FileName<DateTimeOriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.png
fi

if ls *.mp4 1> /dev/null 2>&1; then
    echo "Naming '.mp4' files..."
    exiftool -m '-FileName<CreateDate' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.mp4
fi

if ls *.MP4 1> /dev/null 2>&1; then
    echo "Naming '.MP4' files..."
    exiftool -m '-FileName<CreateDate' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.MP4
fi

if ls *.MTS 1> /dev/null 2>&1; then
    echo "Naming '.MTS' files..."
    exiftool -m '-FileName<datetimeoriginal' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.MTS
fi

if ls *.mov 1> /dev/null 2>&1; then
    echo "Naming '.mov' files..."
    exiftool -m '-FileName<CreateDate' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %%f.%%e" *.mov
fi

if ls *.MOV 1> /dev/null 2>&1; then
    echo "Naming '.MOV' files..."
    exiftool -m '-FileName<CreateDate' -r -d "%Y-%m-%d %H-%M-%S%%-c${name} - %f.%%e" *.MOV
fi

if ls *.MTS 1> /dev/null 2>&1; then
    echo "Converting '.MTS' files to '.mp4'..."
    for file in *.MTS; do
        ffmpeg -i "$file" -q:v 0 "${file%.*}.mp4"
        rm "$file"
    done
fi

if ls *.mov 1> /dev/null 2>&1; then
    echo "Converting '.mov' files to '.mp4'..."
    for file in *.mov; do
        ffmpeg -i "$file" -q:v 0 "${file%.*}.mp4"
        rm "$file"
    done
fi

if ls *.MOV 1> /dev/null 2>&1; then
    echo "Converting '.MOV' files to '.mp4'..."
    for file in *.MOV; do
        ffmpeg -i "$file" -q:v 0 "${file%.*}.mp4"
        rm "$file"
    done
fi

if ls *.heic 1> /dev/null 2>&1; then
    echo "Converting '.heic' files to '.jpg'..."
    for file in *.heic; do
        heif-convert -q 99 "$file" "${file%.*}.jpg" ;
        rm "$file"
    done
fi

if ls *.HEIC 1> /dev/null 2>&1; then
    echo "Converting '.HEIC' files to '.jpg'..."
    for file in *.HEIC; do
        heif-convert -q 99 "$file" "${file%.*}.jpg" ;
        rm "$file"
    done
fi
