#!/bin/sh

name=$(nitropy nk3 secrets list | rg -o '^[0-9]{2}\. [^\t]*' | sd '^[0-9]{2}\. ' '' | rofi -dmenu -p "Nitrokey" -i)
nitropy nk3 secrets get-password "$name" | rg password | sd 'password            : ' '' | sd '\n' '' | xclip -sel clip
