#!/bin/sh

sudo apt update
sudo apt install -y \
    zsh zsh-syntax-highlighting \
    neovim \
    alacritty \
    exa \
    ripgrep silversearcher-ag \
    libimage-exiftool-perl perl-doc \
    git \
    bat \
    rofi \
    fd-find \
    gnome-keyring seahorse pinentry-gnome3 libpam-gnome-keyring \
    dbus dbus-x11 \
    pass pass-extension-otp
sudo apt upgrade
