#!/bin/sh

sudo apt update
sudo apt install -y \
    zsh zsh-syntax-highlighting \
    neovim \
    alacritty \
    exa \
    ripgrep silversearcher-ag \
    libimage-exiftool-perl perl-doc \
    git \
    bat \
    rofi \
    pass pass-extension-otp
sudo apt upgrade
