[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[[language]]
name = "zig"
formatter = { command = "zig", args = ["fmt", "--stdin"] }
auto-format = true

[[language]]
name = "go"
formatter = { command = "go-fmt", args = [""] }
auto-format = true

[[language]]
name = "markdown"
file-types = ["md"]
formatter = { command = "prettier", args = ["--parser", "markdown"]}
auto-format = true

[[language]]
name = "latex"
file-types = ["tex"]
auto-format = true
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-latex", "--write"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--plugin", "/home/david/.bun/install/global/node_modules/prettier-plugin-jinja-template/lib/index.js", "--parser", "jinja-template"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true
scope = "source.mylang"
file-types = ["js", "ts"]

[language-server.bash]
command = "sh-lsp"

[[language]]
name = "bash"
file-types = ["sh", "bash"]
auto-format = true
formatter = { command = "shfmt", args = ["-"] }

[language-server.pyright]
command = "pyright-lsp"

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = [ "pylsp", "pyright", "ruff" ]
auto-format = true
formatter = { command = "ruff", args = ["format", "--preview", "--line-length=120", "-"] }

[[language]]
roots = []
name = "vim"
scope = "source.vim"
file-types = [
  "vim",
]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "vim"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-vim", rev = "bc1364d922952138957a62105171ed68e73fbb6c" }

[[language]]
roots = []
name = "lilypond"
scope = "source.ly"
file-types = ["ly"]
comment-tokens = "%"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "ly", args = ["reformat"] }

[[grammar]]
name = "lilypond"
source = { git = "https://github.com/nwhetsell/tree-sitter-lilypond", rev = "49682b4a4dc163016a43d70f7e3d0182f438fad0" }

[[language]]
roots = []
name = "lco"
scope = "source.lco"
file-types = ["lco"]
comment-tokens = "%"
auto-format = true
indent = { tab-width = 2, unit = "  " }
